coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        if_ci_failed: error #success, failure, error, ignore
    patch:
      default:
        if_ci_failed: ignore #success, failure, error, ignore
